### ISSUE TITLE
Does the app still work? 

### ISSUE THREAD

**Issue by varkon256** [opengeos/streamlit-geospatial#116]
I'm trying to create a timelapse but the page is stuck in computing and doesn't generate a timelapse. 

<img width="304" alt="image" src="https://user-images.githubusercontent.com/24356659/230788402-592fae11-646d-40b4-ad6b-53f841e709ba.png">

**Comment by zxdawn** [comment]
I also got an error:

![image](https://user-images.githubusercontent.com/30388627/232812082-19a867e2-4a53-4de7-a9bc-94ba0b0804e0.png)

**Comment by giswqs** [comment]
App rebooted. Try again. https://streamlit.gishub.org/
