### ISSUE TITLE
None of the apps are opening on the website 

### ISSUE THREAD

**Issue by priyapatel1** [opengeos/streamlit-geospatial#118]
I get an error on every app I select, the error looks like the following: 

"Oh no.
Error running app. If this keeps happening, please [contact support](https://github.com/giswqs/streamlit-geospatial/issues/new)."

**Comment by bangpradyumna** [comment]
Getting the same error. It seems that the app is running out of memory

**Comment by giswqs** [comment]
https://huggingface.co/spaces/giswqs/Streamlit
