### ISSUE TITLE
Earth Engine Authenticate

### ISSUE THREAD

**Issue by keanteng** [opengeos/streamlit-geospatial#124]
I am cloning the repository and try to host this on streamlit app and everything works fine except the Earth Engine authentication 
<img width="398" alt="image" src="https://github.com/giswqs/geemap-streamlit/assets/120152624/0785e120-ffe7-4ad5-b452-9c8c4ed03712">
The screen always stuck and here even if I have included the secret key by clicking on the authentication link on streamlit app secret. 

To ensure the secret key can be detected, on the timelapse page I also put in a line of code as follow:
`os.environ["EARTHENGINE_TOKEN"] == st.secrets["EARTHENGINE_TOKEN"]`

But things does not change. I hope you can help me to look into this issue, my app link is here: https://sr2wzfkohavxdtmxglzrih.streamlit.app/

**Comment by giswqs** [comment]
See https://huggingface.co/spaces/giswqs/solara-geemap
