### ISSUE TITLE
the website can't open

### ISSUE THREAD

**Issue by wanghua18** [opengeos/streamlit-geospatial#128]
https://geospatial.streamlit.app/
this website can't open

**Comment by giswqs** [comment]
https://huggingface.co/spaces/giswqs/Streamlit

**Comment by wanghua18** [comment]
![8a5e32e44b3ed6613da5b96e41f3989](https://github.com/opengeos/streamlit-geospatial/assets/158032499/79fe469d-b5a4-4db8-8662-d15fbd3d2296)
May I ask why there are so many black holes in the generated animation?

**Comment by giswqs** [comment]
Clouds removal
