### ISSUE TITLE
keyword search lets one map to select, but then fails in Python code

### ISSUE THREAD

**Issue by aytvill** [opengeos/streamlit-geospatial#132]
when I select Basemaps, then select keyword _food_  - it finds one map qms.Esri World Topo.

but when I select that map, it fails with stack trace

```
AttributeError: 'NoneType' object has no attribute 'strip'
Traceback:

File "/usr/local/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 565, in _run_script
    exec(code, module.__dict__)
File "/home/user/app/pages/6_🗺️_Basemaps.py", line 63, in <module>
    app()
File "/home/user/app/pages/6_🗺️_Basemaps.py", line 58, in app
    m.add_xyz_service(tile)
File "/usr/local/lib/python3.10/site-packages/leafmap/foliumap.py", line 2096, in add_xyz_service
    if attribution.strip() == "":
```

normally there should be error handling

**Comment by aytvill** [comment]
after fix applied in #134 , stack trace disappeared, only error message is shown (see below)
if that's expected behavior then lets consider it as case closed, thank you

![Screenshot 2024-07-02 at 22-01-32 Streamlit - a Hugging Face Space by giswqs](https://github.com/opengeos/streamlit-geospatial/assets/75947037/68afe959-4cfd-40f5-9f02-99609dcba86a)

**Comment by giswqs** [comment]
Yes, that's the expected behavior from the error hanlding. I don't know what's wrong with the particular basemap. Other basemaps work fine.

**Comment by aytvill** [comment]
no worries, I realize this app/code is neither industrial, nor for "retail users", my sole point was to make it _not failing_ (with stack traces), thank you again for your time and effort
