### ISSUE TITLE
https://geospatial.streamlitapp.com can not be accessed.

### ISSUE THREAD

**Issue by lllllrrrr** [opengeos/streamlit-geospatial#139]
https://geospatial.streamlitapp.com can not be accessed.
![屏幕截图 2024-08-02 170455](https://github.com/user-attachments/assets/b5e5b51c-8175-4616-abc3-e73d089687a0)

**Comment by giswqs** [comment]
See https://huggingface.co/spaces/giswqs/Streamlit
